Chore/cli signatures
omnibenchmark/omni-py pull request #4
Opened 2024-05-17 17:01 UTC by almutlue

## Code signatures for cli and general code structure

This PR contains:
1. __Code signature for the cli__: 
- use, e.g. `ob --help`
- cli groups (can be renamed in `cli/main.py`
2.__repo structure__:
- very broad and simple structure suggestion for python code

__Open questions__: 
Both cli groups and the repo structure are thought as a discussion basis and suggestions, feedback is very welcome. Alternatively we could organize the cli in one file, but with this number of commands this gets long and easily messy?

2024-05-21 12:33 UTC, DanInci requested changes

2024-05-22 11:22 UTC, retogerber commented on omni/cli/io.py
> +def checksum_files(
Do we need a dedicated function for this? It could be done automatically when downloading.

2024-05-24 10:05 UTC, imallona commented on pyproject.toml
please replace with `omni-schema = {git = "https://github.com/omnibenchmark/omni-schema.git", rev = "e3daebe9f75a6225adb674da5efaa477981baa1e"}`

2024-05-24 10:13 UTC, imallona commented
Please consider updating [the license](https://github.com/omnibenchmark/omni-py/blob/483dbfb3b860b6abced6b61d0b465768bafed917/LICENSE#L189) to something like `2024 Omnibenchmark team (our names here, including Mark)`

2024-05-24 10:34 UTC, almutlue commented on omni/cli/main.py
> +    # NOTE: We probably also need a gitlab url? Not sure about module_name?
It is about starting/setting up a new module right? So at this time point the module does not belong to a benchmark, yet and does not have an id. This function will fetch a gitlab template and set up a new project. The benchmark yaml will be used to prefill requirements like which tests to run in the cicd. The "benchmarker" will decide to include the module afterwards into the next benchmark version and then the module will get an id.

2024-05-24 10:36 UTC, almutlue commented on omni/cli/io.py
> +def checksum_files(
@imallona do you have an opinion on this? I agree that this could be done automatically when downloading. Are there other use cases?

2024-05-24 10:44 UTC, imallona commented on omni/cli/io.py
> +def checksum_files(
I agree it will be done automatically after download, but I think it would be good to have it separate/atomized and called by the download tool, when applicable. Because a checksum could be called (automated or not) to check integrity in several scenarios (after download, diff-ing, etc)

2024-05-24 11:01 UTC, retogerber commented on omni/cli/io.py
> +def checksum_files(
right, I didn't think about those scenarios. Let's keep it then.

2024-05-24 11:27 UTC, retogerber approved these changes

2024-05-24 11:41 UTC, imallona approved these changes

2024-05-24 11:45 UTC, merged